runconfig:
  - type: 0
    threads: 1
    numDP: 5000
    numCL: 55
  - type: 1
    threads: 2
    numDP: 5000
    numCL: 55
  - type: 1
    threads: 4
    numDP: 5000
    numCL: 55
  - type: 2
    threads: 2
    numDP: 5000
    numCL: 55
  - type: 2
    threads: 4
    numDP: 5000
    numCL: 55