runconfig:
  - type: 0
    threads: 1
  - type: 1
    threads: 2
  - type: 1
    threads: 4
  - type: 2
    threads: 2
  - type: 2
    threads: 4
  - type: 3
    threads: 2
  - type: 3
    threads: 4
  - type: 3
    threads: 8